"""Initial_1

Revision ID: 52ab970b9e13
Revises: 
Create Date: 2021-01-26 15:52:17.335209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ab970b9e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False, comment='城市ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='城市名稱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='使用者ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='使用者名稱'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='使用者居住城市ID'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='訊息ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='訊息的留言者ID'),
    sa.Column('title', sa.String(length=30), nullable=False, comment='訊息標題'),
    sa.Column('content', sa.String(length=100), nullable=False, comment='訊息內容'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
